import { createSlice } from "@reduxjs/toolkit";
import type { PayloadAction } from "@reduxjs/toolkit";
import { fetchMenuCategoriesAsync, fetchMenuItemsAsync } from "./async-thunk";

// Define a type for the slice state
export interface MenuItemState {
  itemId: string;
  category: string;
  name: string;
  description?: string;
  price: number;
  quantity: number;
}
interface MenuState {
  items: MenuItemState[];
  categories: string[];
  currentCategory: string;
  loading: boolean;
  error: string | null;
  totalPrice: number;
  tableNumber?: number;
  cartOpen: boolean;
}
// Define the initial state using that type
const initialState: MenuState = {
  items: [],
  categories: [],
  currentCategory: "",
  loading: false,
  error: null,
  totalPrice: 0,
  tableNumber: undefined,
  cartOpen: true
};

export const menuItemSlice = createSlice({
  name: "menuItem",
  // `createSlice` will infer the state type from the `initialState` argument
  initialState,
  reducers: {
    selectCategory: (state, action: PayloadAction<string>) => {
      state.currentCategory = action.payload;
    },
    addItemOrIncrement: (state, action: PayloadAction<MenuItemState>) => {
      const currentItem = state.items.find(
        (item) => item.itemId === action.payload.itemId,
      );
      if (currentItem) {
        currentItem.quantity += 1;
        state.totalPrice += currentItem.price;
      }
    },
    removeItemOrDecrement: (state, action: PayloadAction<MenuItemState>) => {
      const existingItem = state.items.find(
        (item) => item.itemId === action.payload.itemId,
      );
      if (existingItem) {
        if (existingItem.quantity > 1) {
          existingItem.quantity -= 1;
          state.totalPrice -= existingItem.price;
        } else {
          state.totalPrice -= existingItem.price;
          existingItem.quantity = 0; // Set quantity to 0 before removing
        }
      }
    },
    removeItem: (state, action: PayloadAction<MenuItemState>) => {
      const itemToRemove = state.items.find((item) => item.itemId === action.payload.itemId);
      if (itemToRemove) {
        state.totalPrice -= itemToRemove.price * itemToRemove.quantity;
        itemToRemove.quantity = 0; // Set quantity to 0 before removing
      }
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchMenuItemsAsync.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(
        fetchMenuItemsAsync.fulfilled,
        (state, action: PayloadAction<MenuItemState[]>) => {
          state.loading = false;
          state.items = action.payload;
          if (state.currentCategory.length === 0) {
            state.items = action.payload;
          }
        },
      )
      .addCase(fetchMenuItemsAsync.rejected, (state, action) => {
        state.loading = false;
        state.error = action.error.message || null;
      });

    builder
      .addCase(fetchMenuCategoriesAsync.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(
        fetchMenuCategoriesAsync.fulfilled,
        (state, action: PayloadAction<string[]>) => {
          state.loading = false;
          state.categories = action.payload;
        },
      )
      .addCase(fetchMenuCategoriesAsync.rejected, (state, action) => {
        state.loading = false;
        state.error = action.error.message || null;
      });
  },
});

export const { selectCategory, addItemOrIncrement, removeItemOrDecrement, removeItem } = menuItemSlice.actions;
export default menuItemSlice.reducer;
